[UPDATE] Downgrades target SDK to Android 9 (API 28)
Reason for not going 26 is:

```
Lint found 2 errors, 115 warnings. First failure:

/Users/hossain/dev/repos/os-android-apps/trmnl-android/app/src/main/java/ink/trmnl/android/di/TrmnlAppComponentFactory.kt:29: Error: Call requires API level 28 (current min is 26): AppComponentFactory [NewApi]

Version of android.app.AppComponentFactory that works with androidx libraries. Note: This will only work on API 28+ and does not backport AppComponentFactory functionality.
```

Applied changes to fix following:

```
  Lint found 3 errors, 115 warnings. First failure:

  /Users/hossain/dev/repos/os-android-apps/trmnl-android/app/src/main/java/ink/trmnl/android/di/NetworkModule.kt:45: Error: Call requires API level 28 (current min is 26): android.content.pm.PackageInfo#getLongVersionCode [NewApi]
          val versionCode = packageInfo.longVersionCode
                                        ~~~~~~~~~~~~~~~
```

Fixes https://github.com/usetrmnl/trmnl-android/issues/55